Feature/id
growingio/growingio-sdk-android-autotracker-upgrade pull request #1
Opened 2020-12-09 09:03 UTC by styluo

支持cs1, gioid, deviceid从v2版本文件迁移到v3版本文件中

2020-12-09 09:06 UTC, lvyuqiang approved these changes

2020-12-09 11:55 UTC, LitterSun commented on autotracker-upgrade-2to3-cdp/src/main/java/com/growingio/android/sdk/collection/GrowingIO.java
> +    public void keepDeviceIdAndUserId(Context context) {
这个命名可以宽泛一点，比如直接叫upgrade，然后隐藏用户不需要的接口

2020-12-10 02:27 UTC, LitterSun requested changes

2020-12-10 02:27 UTC, LitterSun commented on autotracker-upgrade-2to3-cdp/src/main/java/com/growingio/android/sdk/collection/GrowingIO.java
> +        if (PersistentDataProvider.get().getString(KEEP_ID, "false").equals("true")) {
PersistentDataProvider 初始化需要context对象，应该先要调用ContextProvider#setContext

2020-12-10 03:50 UTC, merged